* Encoding: UTF-8.

EXAMINE VARIABLES=VAR00002 BY VAR00003
  /PLOT BOXPLOT HISTOGRAM NPPLOT SPREADLEVEL(1)
  /COMPARE GROUPS
  /STATISTICS DESCRIPTIVES
  /CINTERVAL 95
  /MISSING LISTWISE
  /NOTOTAL.


*Nonparametric Tests: Independent Samples. 
NPTESTS 
  /INDEPENDENT TEST (VAR00002) GROUP (VAR00003) MANN_WHITNEY 
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.
