* Encoding: UTF-8.

KM 随访时间 BY 治疗
  /STATUS=状态(0)
  /PRINT TABLE MEAN
  /TEST LOGRANK
  /COMPARE OVERALL POOLED.

SURVIVAL TABLE=随访时间 BY 治疗(1 2)
  /INTERVAL=THRU 40 BY 0.1
  /STATUS=状态(0)
  /PRINT=NOTABLE
  /PLOTS (SURVIVAL)=随访时间 BY 治疗.
