* Encoding: UTF-8.

DATASET ACTIVATE DataSet3.
WEIGHT BY 例数.

*Nonparametric Tests: Independent Samples. 
NPTESTS 
  /INDEPENDENT TEST (乳量) GROUP (产妇类型) KRUSKAL_WALLIS(COMPARE=NONE) 
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.
