* Encoding: UTF-8.

DATASET ACTIVATE DataSet0.
WEIGHT BY 例数.

*Nonparametric Tests: Independent Samples. 
NPTESTS 
  /INDEPENDENT TEST (镇静等级) GROUP (组别) MANN_WHITNEY 
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.
